version: 2

project_name: axonhub

dist: .builds

before:
  hooks:
    - /bin/sh -c 'cd deploy && chmod +x *.sh'
    - make build-frontend
    - make generate-schema
    - go mod tidy

builds:
  - id: build
    main: ./cmd/axonhub
    binary: axonhub
    flags:
      - -tags=nomsgpack
    ldflags:
      - -s -w -X github.com/looplj/axonhub/internal/build.Version={{ .Tag }}
      - -s -w -X github.com/looplj/axonhub/internal/build.Commit={{ .Commit }}
      - -s -w -X github.com/looplj/axonhub/internal/build.BuildTime={{ .Date }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

release:
  draft: true
  extra_files:
    - glob: ./config.schema.json

archives:
  - id: archive
    ids: [build]
    formats: [zip]
    files:
      - LICENSE
      - CHANGELOG.md
      - src: deploy/install.sh
        dst: install.sh
      - src: deploy/start.sh
        dst: start.sh
      - src: deploy/stop.sh
        dst: stop.sh
      - src: deploy/restart.sh
        dst: restart.sh
      - src: deploy/upgrade.sh
        dst: upgrade.sh

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: '{{ incpatch .Version }}-snapshot'

changelog:
  sort: asc
  filters:
    exclude:
      - '^examples:'
      - '^ui:'